export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const SUCCESS = 'ALERT_SUCCESS';
export const ERROR = 'ALERT_ERROR';
export const CLEAR = 'ALERT_CLEAR';

export const FETCH_SHOPPINGLISTS_REQUEST = 'FETCH_SHOPPINGLISTS_REQUEST';
export const FETCH_SHOPPINGLISTS_SUCCESS = 'FETCH_SHOPPINGLISTS_SUCCESS';
export const FETCH_SHOPPINGLISTS_FAILURE = 'FETCH_SHOPPINGLISTS_FAILURE';

export const ADD_SHOPPINGLIST_REQUEST = 'ADD_SHOPPINGLIST_REQUEST';
export const ADD_SHOPPINGLIST_SUCCESS = 'ADD_SHOPPINGLIST_SUCCESS';
export const ADD_SHOPPINGLIST_FAILURE = 'ADD_SHOPPINGLIST_FAILURE';

export const EDIT_SHOPPINGLIST_REQUEST = 'EDIT_SHOPPINGLIST_REQUEST';
export const EDIT_SHOPPINGLIST_SUCCESS = 'EDIT_SHOPPINGLIST_SUCCESS';
export const EDIT_SHOPPINGLIST_FAILURE = 'EDIT_SHOPPINGLIST_FAILURE';

export const DELETE_SHOPPINGLIST_REQUEST = 'DELETE_SHOPPINGLIST_REQUEST';
export const DELETE_SHOPPINGLIST_SUCCESS = 'DELETE_SHOPPINGLIST_SUCCESS';
export const DELETE_SHOPPINGLIST_FAILURE = 'DELETE_SHOPPINGLIST_FAILURE';

export const FETCH_A_SHOPPINGLIST_REQUEST = 'FETCH_A_SHOPPINGLIST_REQUEST';
export const FETCH_A_SHOPPINGLIST_SUCCESS = 'FETCH_A_SHOPPINGLIST_SUCCESS';
export const FETCH_A_SHOPPINGLIST_FAILURE = 'FETCH_A_SHOPPINGLIST_FAILURE';

export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

export const FETCH_AN_ITEM_REQUEST = 'FETCH_AN_ITEM_REQUEST';
export const FETCH_AN_ITEM_SUCCESS = 'FETCH_AN_ITEM_SUCCESS';
export const FETCH_AN_ITEM_FAILURE = 'FETCH_AN_ITEM_FAILURE';

export const BUY_ITEM_REQUEST = 'BUY_ITEM_REQUEST';
export const BUY_ITEM_SUCCESS = 'BUY_ITEM_SUCCESS';
export const BUY_ITEM_FAILURE = 'BUY_ITEM_FAILURE';

export const EDIT_ITEM_REQUEST = 'EDIT_ITEM_REQUEST';
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS';
export const EDIT_ITEM_FAILURE = 'EDIT_ITEM_FAILURE';

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';
